use_frameworks!

platform :ios, '8.0'

target 'Rudder-Firebase_Example' do
  pod 'Rudder-Firebase', :path => '../'

  target 'Rudder-Firebase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
